# Numpy
Numerical Python

package python yang digunakan untuk manipulasi data tipe numerik (int dan float)

punya banyak built-in function untuk manipulasi data tipe numerik, seperti:
- mean
- mode
- max, min
- std deviation, variance
- square, squareroot (kuadrat dan pangkat)
- dan lain2

selain itu numpy juga punya satu tipe data baru - numpy array. mirip list tapi bukan list.

---
## Numpy Array
CRUD - create read update delete

create numpy array dengan cara:
- convert sebuah list menjadi array menggunakan `np.array([1,2,3])`
- membuat sebuah array baru menggunakan built-in function:
    1. `np.zeros(5)` --> membuat sebuah array isi angka 0, size 5, ada 5 angka 0.
    2. `np.ones(8)` --> membuat sebuah array isi angka 1, size 8, ada 8 angka 1.
    3. `np.empty(3)` --> membuat sebuah array isi angka random, kita anggap tidak ada angka, size 3.
    4. `np.arange(1,10,3)` --> membuat sebuah array isi angka dari range. cara pakai sama. range(start, stop, step).

In [1]:
import numpy as np

In [2]:
# create
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
list_angka = [1,2,3]
print(list_angka)
print(type(list_angka))

[1, 2, 3]
<class 'list'>


In [4]:
# kalau 2D
list_angka = [[1,2,3],[4,5,6]]
print(list_angka)
print(type(list_angka))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


In [5]:
arr = np.array(list_angka)
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
# cara cara lain membuat numpy array

size = 5

arr = np.ones(size)
print("ones", arr, type(arr))

arr = np.zeros(size)
print("zeros", arr, type(arr))

arr = np.empty(size+3)
print("empty", arr, type(arr))

arr = np.arange(size)
print("arange", arr, type(arr))


ones [1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
zeros [0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
empty [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 7.29240893e-321 3.11525958e-307 1.24610723e-306] <class 'numpy.ndarray'>
arange [0 1 2 3 4] <class 'numpy.ndarray'>


In [28]:
# kita coba buat numpy array 2 dimensi
size = (3, 2)

arr = np.ones(size)
print("ones")
print(arr, type(arr))

arr = np.zeros(size)
print("zeros")
print(arr, type(arr))

arr = np.empty(size)
print("empty, anggap tidak ada isi angkanya")
print(arr, type(arr))

ones
[[1. 1.]
 [1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>
zeros
[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>
empty, anggap tidak ada isi angkanya
[[0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>


In [13]:
# np.arange seperti menggunakan range
# bisa diisi 1 angka untuk membuat angka urut dari 0 sampai angka-1
# bisa diisi 2 angka start stop untuk membuat angka urut dari start sampai stop-1
# bisa diisi 3 angka start stop step untuk membuat angka urut dari start sampai stop-1 dan setiap angka berikut bertambah sebanyak step

start = 5
stop = 60
step = 7

arr = np.arange(start)
print(arr)

arr = np.arange(start, stop)
print(arr)

arr = np.arange(start, stop, step)
print(arr)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59]
[ 5 12 19 26 33 40 47 54]


In [14]:
# edit (update)
# append, delete, sort
print(arr)

[ 5 12 19 26 33 40 47 54]


### append

In [15]:
np.append(arr, [5,15,20])

array([ 5, 12, 19, 26, 33, 40, 47, 54,  5, 15, 20])

In [16]:
print(arr)

[ 5 12 19 26 33 40 47 54]


perhatikan, hasil append tidak merubah data array kita yang ada di variable `arr`

untuk membuat sebuah array hasil dari array awal kita + append data baru, kita perlu re-assign variable nya.

In [17]:
arr = np.append(arr, [9,8,7])
print(arr)

[ 5 12 19 26 33 40 47 54  9  8  7]


### delete
menghapus menggunakan posisi

In [18]:
arr = np.delete(arr, 5)
print(arr)

[ 5 12 19 26 33 47 54  9  8  7]


### sort

In [19]:
arr = np.sort(arr)
print(arr)

[ 5  7  8  9 12 19 26 33 47 54]


angka negatif juga bisa dimasukkan ke sebuah numpy array. angka float juga bisa.

### ndim, size, shape
tiga cara untuk melihat (read) sebuah numpy array punya detail
- ndim - dimensi
- size - jumlah angka yang ada di dalam numpy array
- shape - bentuknya... bentuknya? kalau numpy array lebih dari 1 dimensi, kita bisa tau ada berapa baris, berapa kolom... ada berapa jumlah angka di setiap dimensi

In [21]:
print(arr.ndim)
print(arr.size)
print(arr.shape)

1
10
(10,)


sebenarnya dari shape kita sudah kelihatan array nya punya berapa dimensi

## Reshape
mengubah shape sebuah numpy array

In [33]:
arr = np.arange(-50,80,11)
print(arr)

[-50 -39 -28 -17  -6   5  16  27  38  49  60  71]


In [34]:
arr.size

12

In [38]:
# ukuran size sebelum dan sesudah reshape harus sama
# misal ukuran sebelumnya 12, maka reshape 2dimensi bisa jadi (3,4) atau (4,3) (6,2) (2,6) (1,12) (12,1)
print(arr.reshape((3,4)))
print(arr.size)

[[-50 -39 -28 -17]
 [ -6   5  16  27]
 [ 38  49  60  71]]
12


In [40]:
for shape in [(4,3), (6,2), (2,6), (1,12), (12,1), (12,)]:
    print(arr.reshape(shape))

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]
[[-50 -39]
 [-28 -17]
 [ -6   5]
 [ 16  27]
 [ 38  49]
 [ 60  71]]
[[-50 -39 -28 -17  -6   5]
 [ 16  27  38  49  60  71]]
[[-50 -39 -28 -17  -6   5  16  27  38  49  60  71]]
[[-50]
 [-39]
 [-28]
 [-17]
 [ -6]
 [  5]
 [ 16]
 [ 27]
 [ 38]
 [ 49]
 [ 60]
 [ 71]]
[-50 -39 -28 -17  -6   5  16  27  38  49  60  71]


bisa dilihat kalau jumlah angka (size) sebelum dan sesudah reshape selalu sama, harus selalu sama. jumlah dimensi boleh berubah 1d, 2d, 3d, ... bebas

## Indexing dan Slicing
sejauh ini kita sudah bisa membuat, baca properti, ubah bentuk, nambah, hapus, dan sortir angka2 numpy array. indexing dan slicing akan membuat kita bisa mengambil/ membaca 1 atau banyak angka dalam sebuah numpy array.

ngambil 1, namanya indexing

ngambil banyak, namanya slicing

In [41]:
arr = arr.reshape((4,3))
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [42]:
# indexing
# misal mau ambil angka -6
# array kita punya 2Dimensi. Dimensi pertama berisi 4 numpy array. angka yang kita mau ambil ada di numpy array ke berapa?
#    ada di numpy array ke-2. barang ke-2 punya index 1. jadi kita gunakan index 1 untuk dapat array ke-2
# di dalam array ke-2 ini, angka yang kita mau ambil ada di posisi ke berapa? 
#    dia ada di posisi ke-2 berarti index 1 lagi. jadi kita gunakan index (1,1) untuk dapat array ke-2 dan angka ke-2 di array tersebut

arr[1,1]

-6

In [43]:
# misal maunya ambil angka 5, masih di array ke-2 index 1, tapi sekarang di posisi ke-3 index 2
# jadi kita gunakan index (1,2)
arr[1,2]

5

In [44]:
# slicing
# slicing mau ambil beberapa item sekaligus, misalkan kita mau ambil -6 dan 5 duaduanya
# berarti kita mau ambil index (1,1) dan index (1,2)
# cara tulisnya kita gabung, 
#   dimensi pertama angkanya sama 1
#   dimensi kedua angkanya beda 1 dan 2, jadi kita tulis 1:2 tapi karena angka terakhir tidak termasuk, kita +1 ke angka terakhir jadi 1:3
arr[1,1:3]

array([-6,  5])

In [45]:
# kalau selain -6 dan 5 kita juga mau ambil angka 27 dan 38
# berarti kita mau ambil index (1,1) (1,2) (2,1) (2,2)
# kita gabungkan indexnya jadi (1:3, 1:3)
arr[1:3, 1:3]

array([[-6,  5],
       [27, 38]])

In [46]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [47]:
arr[1:3]

array([[-17,  -6,   5],
       [ 16,  27,  38]])

In [48]:
arr[1:3, 1]

array([-6, 27])

In [49]:
arr[1:3, 2]

array([ 5, 38])

In [50]:
arr[1:3, 1:3]

array([[-6,  5],
       [27, 38]])

In [51]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [52]:
arr[0,1]

-39

In [53]:
arr[3,1]

60

In [54]:
arr[[0,3],1]

array([-39,  60])

In [55]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


### break 10 menit (20.05 WIB)
latihan pendek: buatlah numpy array seperti di atas, lalu gunakan teknik slicing untuk mengambil angka -17 dan 71

setelah ini kita bahas lalu lanjut ke teknik numpy lainnya

In [56]:
arr = np.array([[-50, -39, -28],
                [-17,  -6,   5],
                [ 16,  27,  38],
                [ 49,  60,  71]])
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [57]:
# (1,0)
# (3,2)

arr[[1,3], [0,2]]

array([-17,  71])

In [58]:
# index hitung dari belakang, -1 untuk angka terakhir
# (1,0)
# (-1,-1)

arr[[1,-1], [0,-1]]

array([-17,  71])

### membuat array dari array
vstack, hstack, numpukin beberapa array jadi satu secara vertical/ horizontal. kalau secara vertical, jumlah kolom harus sama. kalau secara horizontal, jumlah baris harus sama.

vsplit, hsplit, motong sebuah array jadi beberapa bagian yang ukurannya sama, potongan bisa secara vertical/ horizontal.

view. membuat nama lain untuk numpy array yang sama. seperti punya 1 rumah tapi 2 alamat. view membuat alamat baru untuk rumah yang sama.

copy. membuat duplikat sebuah numpy array. copy membuat rumah yang sama persis di alamat yang baru.

In [59]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [60]:
arr_b = np.array([1,2,3])

print(arr_b)

[1 2 3]


In [62]:
np.vstack((arr, arr_b))

array([[-50, -39, -28],
       [-17,  -6,   5],
       [ 16,  27,  38],
       [ 49,  60,  71],
       [  1,   2,   3]])

In [63]:
np.vstack((arr_b, arr, arr_b, [4,5,6]))

array([[  1,   2,   3],
       [-50, -39, -28],
       [-17,  -6,   5],
       [ 16,  27,  38],
       [ 49,  60,  71],
       [  1,   2,   3],
       [  4,   5,   6]])

In [64]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [66]:
np.hstack((arr, [[6],[7],[8],[9]]))

array([[-50, -39, -28,   6],
       [-17,  -6,   5,   7],
       [ 16,  27,  38,   8],
       [ 49,  60,  71,   9]])

In [67]:
arr_c = np.array([6,7,8,9]).reshape((4,1))
print(arr_c)

[[6]
 [7]
 [8]
 [9]]


In [68]:
np.hstack((arr, arr_c))

array([[-50, -39, -28,   6],
       [-17,  -6,   5,   7],
       [ 16,  27,  38,   8],
       [ 49,  60,  71,   9]])

In [69]:
np.hstack((arr, arr_c,arr_c,arr_c))

array([[-50, -39, -28,   6,   6,   6],
       [-17,  -6,   5,   7,   7,   7],
       [ 16,  27,  38,   8,   8,   8],
       [ 49,  60,  71,   9,   9,   9]])

In [70]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [71]:
np.vsplit(arr, 4)

[array([[-50, -39, -28]]),
 array([[-17,  -6,   5]]),
 array([[16, 27, 38]]),
 array([[49, 60, 71]])]

In [72]:
a1,a2,a3,a4 = np.vsplit(arr, 4)

print(a1)

[[-50 -39 -28]]


In [73]:
print(a2)

[[-17  -6   5]]


In [74]:
print(arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [75]:
np.hsplit(arr, 3)

[array([[-50],
        [-17],
        [ 16],
        [ 49]]),
 array([[-39],
        [ -6],
        [ 27],
        [ 60]]),
 array([[-28],
        [  5],
        [ 38],
        [ 71]])]

In [76]:
a1,a2,a3 = np.hsplit(arr, 3)

print(a3)

[[-28]
 [  5]
 [ 38]
 [ 71]]


In [77]:
# view
random_arr = arr.view()

In [78]:
print(random_arr)

[[-50 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [79]:
# kalau kita ubah arr, ramdom_arr ikut berubah
# begitu pula sebaliknya
random_arr[0,0] = 100

In [80]:
print(random_arr)

[[100 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [81]:
print(arr)

[[100 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [82]:
# copy
arr_copy = arr.copy()

In [83]:
print(arr_copy)

[[100 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [84]:
arr_copy[0,0] = 0
print(arr_copy)

[[  0 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [85]:
# data awal kita arr tidak disentuh
print(arr)

[[100 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


## array operations
operasi matematik dengan numpy array semua bisa

kalau list tidak bisa

In [86]:
print(arr)

[[100 -39 -28]
 [-17  -6   5]
 [ 16  27  38]
 [ 49  60  71]]


In [87]:
arr = arr + 100
print(arr)

[[200  61  72]
 [ 83  94 105]
 [116 127 138]
 [149 160 171]]


In [88]:
print(list_angka)

[[1, 2, 3], [4, 5, 6]]


In [89]:
list_angka + 3

TypeError: can only concatenate list (not "int") to list

In [90]:
np.array(list_angka) + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [91]:
# kalau mau nambahinnya beda2 juga gk masalah
print(arr)

[[200  61  72]
 [ 83  94 105]
 [116 127 138]
 [149 160 171]]


In [92]:
arr_tambahan = np.ones(arr.shape) * 10
print(arr_tambahan)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [93]:
arr_tambahan[0,1] = arr_tambahan[0,1] + 10

In [94]:
print(arr_tambahan)

[[10. 20. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [95]:
arr + arr_tambahan

array([[210.,  81.,  82.],
       [ 93., 104., 115.],
       [126., 137., 148.],
       [159., 170., 181.]])

In [96]:
print(arr + 10 * 3 / 15 - 70)

[[132.  -7.   4.]
 [ 15.  26.  37.]
 [ 48.  59.  70.]
 [ 81.  92. 103.]]


### more array operations
selain aritmatik, ada juga built-in function numpy yang bisa cari jumlah, rata2, dan lainnya:
- sum
- min, max
- mean
- product
- std deviation
- and more...

In [97]:
print(arr)

[[200  61  72]
 [ 83  94 105]
 [116 127 138]
 [149 160 171]]


In [98]:
# berapa sih jumlah semua angka di arr ini?
arr.sum()

1476

In [99]:
# sum per baris
arr.sum(axis=0)

# baris 1 + baris 2 + baris 3 + baris 4 = berikut

array([548, 442, 486])

In [100]:
# sum per kolom
arr.sum(axis=1)

# kolom 1 + kolom 2 + kolom 3 = berikut

array([333, 282, 381, 480])

In [106]:
print(arr)

[[200  61  72]
 [ 83  94 105]
 [116 127 138]
 [149 160 171]]


In [103]:
# mean, min, max
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

123.0
[137.  110.5 121.5]
[111.  94. 127. 160.]


In [104]:
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

61
[83 61 72]
[ 61  83 116 149]


In [105]:
print(arr.max())
print(arr.max(axis=0))
print(arr.max(axis=1))

200
[200 160 171]
[200 105 138 171]


# Matrix
numpy array 2 dimensi yang berisi angka semua, dan jumlah angka di setiap barisnya sama.

In [107]:
m1 = np.array([ [10, 12, 5, 7, 30],
                [2, 3, 5, 1, 7],
                [5, 2, 15, 2, 0]])
print(m1)

[[10 12  5  7 30]
 [ 2  3  5  1  7]
 [ 5  2 15  2  0]]


In [108]:
m2 = np.array([ [2000,5000,3000],
                [1200,3000,1800],
                [3000,10000,7000]])
print(m2)

[[ 2000  5000  3000]
 [ 1200  3000  1800]
 [ 3000 10000  7000]]


In [113]:
# jumlah profit minggu ini
profit = m2[:,-1].reshape((1,3))
print(profit)

[[3000 1800 7000]]


In [116]:
profit.dot(m1)

array([[ 68600,  55400, 129000,  36800, 102600]])

### Transpose
kolom jadi baris, baris jadi kolom

### Reshape
bentuk berubah, tapi dia tidak ingat teman sebaris/kolom sebelumnya

In [117]:
print(m1)

[[10 12  5  7 30]
 [ 2  3  5  1  7]
 [ 5  2 15  2  0]]


In [118]:
# transpose
m1.T

array([[10,  2,  5],
       [12,  3,  2],
       [ 5,  5, 15],
       [ 7,  1,  2],
       [30,  7,  0]])

transpose 2 kali balik ke awal

In [121]:
m1.T.T

array([[10, 12,  5,  7, 30],
       [ 2,  3,  5,  1,  7],
       [ 5,  2, 15,  2,  0]])

In [120]:
# reshape
m1.reshape((5,3))

array([[10, 12,  5],
       [ 7, 30,  2],
       [ 3,  5,  1],
       [ 7,  5,  2],
       [15,  2,  0]])

reshape tidak mempedulikan posisi angka apakah dulunya sebaris/ sekolom. dia urutin aja angkanya ke bentuk yang baru.

In [ ]:
## Break 10 menit (21.00 WIB)
##    lanjut ke Pandas ATAU review materi sesi 1-4